execfile("miow.keys")

execfile("core/miow.init")
register_ipy_files(['examples'], '.ipy')
register_ipy_files(['.'], 'miow.init')

execfile("widgets/miow.init")

#execfile("examples/miow.init")



COMMAND_LIST += [
        #("new interpreter editor", "", 0.0, 'self.new_widget_InterpreterEditor("")'),
        ("close application", "", 0.0, "MAIN_WINDOW.close()"),
        ("close current widget", "", 0.0, "MAIN_WINDOW._main_tab.removeTab(MAIN_WINDOW._main_tab.currentIndex())"),
               ]
