INIT_FOLDERS += ['./widgets']

REGISTERED_WIDGETS += [
    {"module": "core.InterpreterEditor",
     "widget": "InterpreterEditor"}
    ]

execfile("miow.keys")




COMMAND_LIST += [
        #("new interpreter editor", "", 0.0, 'self.new_widget_InterpreterEditor("")'),
        ("close application", "", 0.0, "MAIN_WINDOW.close()"),
        ("close current widget", "", 0.0, "MAIN_WINDOW._main_tab.removeTab(MAIN_WINDOW._main_tab.currentIndex())"),
               ]
